### ISSUE TITLE
kill me X_X

### ISSUE THREAD

**Issue by Skydreamer** [vnaydionov/yb-orm#15] opened 2015-04-15 17:28 UTC

**Comment by vnaydionov** [comment] 2015-04-15 18:00
it works ok when join condition is explicitly given:

      SELECT COUNT(*) CNT FROM (SELECT T_ORM_TEST.ID, T_ORM_TEST.A, T_ORM_TEST.B, T_ORM_TEST.C, T_ORM_TEST.D, T_ORM_XML.ID, T_ORM_XML.ORM_TEST_ID, T_ORM_XML.B FROM T_ORM_TEST JOIN T_ORM_XML ON (T_ORM_TEST.ID = T_ORM_XML.ORM_TEST_ID)) X

but fails to produce correct SQL for the implicit join condition:

    SELECT COUNT(*) CNT FROM (SELECT T_ORM_TEST.ID, T_ORM_TEST.A, T_ORM_TEST.B, T_ORM_TEST.C, T_ORM_TEST.D, T_ORM_XML.ID, T_ORM_XML.ORM_TEST_ID, T_ORM_XML.B FROM T_ORM_TEST JOIN T_ORM_XML ON ) X

**Comment by vnaydionov** [comment] 2015-04-15 18:04
closing as a duplicate of #7

**Closed by vnaydionov** 2015-04-15 18:04 UTC
Labels: duplicate
